import React, { useEffect, useState } from 'react';
import { Pressable, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';

const API = process.env.EXPO_PUBLIC_API_URL ?? 'http://localhost:4000/api/v1';
type Dashboard = { counts: { customers: number; products: number; sales: number }; lowStock: { product: { name: string }; stock: number }[] };
type Resource = { id: string; name?: string; title?: string; email?: string; status?: string; amount?: number; category?: string; message?: string };
const modules = ['Resumen', 'Clientes', 'Productos', 'Proveedores', 'Empleados', 'Proyectos', 'Finanzas', 'Incidencias', 'Notificaciones'];

export default function App() {
  const [token, setToken] = useState(''); const [email, setEmail] = useState('admin@demo.local'); const [password, setPassword] = useState('Admin123!');
  const [active, setActive] = useState('Resumen'); const [userId, setUserId] = useState(''); const [dashboard, setDashboard] = useState<Dashboard | null>(null); const [rows, setRows] = useState<Resource[]>([]); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const [formValue, setFormValue] = useState('');
  const endpoint: Record<string, string> = { Clientes: 'customers', Productos: 'products', Proveedores: 'suppliers', Empleados: 'employees', Proyectos: 'projects', Finanzas: 'finance/transactions', Incidencias: 'incidents', Notificaciones: 'notifications' };
  async function login() { setBusy(true); setError(''); try { const response = await fetch(`${API}/auth/login`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ email, password }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error?.message ?? 'No se pudo iniciar sesión'); setUserId(data.user.id); setToken(data.token); } catch (err) { setError(err instanceof Error ? err.message : 'Error de conexión'); } finally { setBusy(false); } }
  async function loadModule(module: string) { setActive(module); if (module === 'Resumen' || !token) return; setError(''); const response = await fetch(`${API}/${endpoint[module]}`, { headers: { Authorization: `Bearer ${token}` } }); const data = await response.json(); if (!response.ok) return setError(data.error?.message ?? 'No se pudo cargar el módulo'); setRows(Array.isArray(data) ? data : []); }
  async function createRecord() { const path = endpoint[active]; if (!path || !formValue.trim()) return; setBusy(true); const payload = active === 'Finanzas' ? { type: 'income', category: formValue, amount: 1 } : active === 'Incidencias' ? { title: formValue } : active === 'Productos' ? { sku: `SKU-${Date.now()}`, name: formValue, price: 0, cost: 0 } : active === 'Proyectos' ? { name: formValue, ownerId: userId } : { name: formValue }; const response = await fetch(`${API}/${path}`, { method: 'POST', headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }); const data = await response.json(); setBusy(false); if (!response.ok) return setError(data.error?.message ?? 'No se pudo crear el registro'); setFormValue(''); loadModule(active); }
  useEffect(() => { if (!token) return; fetch(`${API}/dashboard`, { headers: { Authorization: `Bearer ${token}` } }).then(response => response.json()).then(setDashboard).catch(() => setError('No se pudo cargar el dashboard')); }, [token]);
  useEffect(() => { if (token && active !== 'Resumen') loadModule(active); }, [token, active]);
  if (!token) return <SafeAreaView style={styles.login}><View style={styles.loginPanel}><Text style={styles.eyebrow}>ERP PLATFORM</Text><Text style={styles.title}>Operaciones claras.</Text><Text style={styles.subtitle}>Ventas, inventario y gestión empresarial en un solo lugar.</Text><TextInput autoCapitalize="none" value={email} onChangeText={setEmail} placeholder="Correo" style={styles.input} /><TextInput secureTextEntry value={password} onChangeText={setPassword} placeholder="Contraseña" style={styles.input} /><Pressable onPress={login} disabled={busy} style={styles.button}><Text style={styles.buttonText}>{busy ? 'Entrando...' : 'Iniciar sesión'}</Text></Pressable>{error ? <Text style={styles.error}>{error}</Text> : null}<Text style={styles.hint}>Demo: admin@demo.local / Admin123!</Text></View></SafeAreaView>;
  return <SafeAreaView style={styles.page}><View style={styles.shell}><View style={styles.sidebar}><Text style={styles.brand}>ERP<Text style={styles.brandAccent}>/</Text>CORE</Text><Text style={styles.company}>EMPRESA DEMO</Text>{modules.map(module => <Pressable key={module} onPress={() => loadModule(module)} style={[styles.navItem, active === module && styles.navActive]}><Text style={[styles.navText, active === module && styles.navTextActive]}>{module}</Text></Pressable>)}<Pressable onPress={() => setToken('')} style={styles.signOut}><Text style={styles.navText}>Salir</Text></Pressable></View><ScrollView contentContainerStyle={styles.content}><Text style={styles.eyebrow}>ESPACIO OPERATIVO</Text><Text style={styles.heading}>{active}</Text>{error ? <Text style={styles.error}>{error}</Text> : null}{active === 'Resumen' ? <><Text style={styles.date}>Indicadores de la empresa activa</Text><View style={styles.metrics}>{[['Clientes', dashboard?.counts.customers ?? 0], ['Productos', dashboard?.counts.products ?? 0], ['Ventas', dashboard?.counts.sales ?? 0]].map(([label, value]) => <View style={styles.metric} key={String(label)}><Text style={styles.metricValue}>{value}</Text><Text style={styles.metricLabel}>{label}</Text></View>)}</View><View style={styles.section}><Text style={styles.sectionTitle}>Alertas de inventario</Text>{dashboard?.lowStock.length ? dashboard.lowStock.map(item => <View style={styles.row} key={item.product.name}><Text style={styles.rowTitle}>{item.product.name}</Text><Text style={styles.alert}>{item.stock} disponibles</Text></View>) : <Text style={styles.empty}>No hay productos bajo mínimo.</Text>}</View></> : <View style={styles.section}><View style={styles.sectionHeader}><Text style={styles.sectionTitle}>{active}</Text>{active !== 'Notificaciones' ? <View style={styles.create}><TextInput value={formValue} onChangeText={setFormValue} placeholder={`Nuevo ${active.toLowerCase()}`} style={styles.smallInput} /><Pressable onPress={createRecord} disabled={busy} style={styles.smallButton}><Text style={styles.buttonText}>Crear</Text></Pressable></View> : null}</View>{rows.length ? rows.map(row => <View style={styles.row} key={row.id}><View><Text style={styles.rowTitle}>{row.name ?? row.title ?? row.message ?? row.category ?? row.id}</Text>{row.email ? <Text style={styles.meta}>{row.email}</Text> : null}</View><Text style={row.status === 'active' || row.status === 'paid' ? styles.good : styles.meta}>{row.status ?? (row.amount !== undefined ? String(row.amount) : '')}</Text></View>) : <Text style={styles.empty}>No hay registros para mostrar.</Text>}</View>}</ScrollView></View></SafeAreaView>;
}

const styles = StyleSheet.create({ login: { flex: 1, backgroundColor: '#eef1ec', justifyContent: 'center', padding: 24 }, loginPanel: { maxWidth: 460, width: '100%', alignSelf: 'center', backgroundColor: '#fff', padding: 36, borderRadius: 8 }, eyebrow: { color: '#167d6a', fontSize: 12, fontWeight: '700', letterSpacing: 1.4 }, title: { color: '#172420', fontSize: 38, fontWeight: '700', marginTop: 12 }, subtitle: { color: '#63706b', fontSize: 16, marginTop: 10, marginBottom: 28 }, input: { borderWidth: 1, borderColor: '#d8dfdb', borderRadius: 5, padding: 13, marginTop: 12, fontSize: 15 }, button: { backgroundColor: '#167d6a', borderRadius: 5, padding: 14, alignItems: 'center', marginTop: 18 }, buttonText: { color: '#fff', fontWeight: '700' }, error: { color: '#b33a3a', marginTop: 14 }, hint: { color: '#84908b', fontSize: 12, marginTop: 22 }, page: { flex: 1, backgroundColor: '#f6f8f5' }, shell: { flex: 1, flexDirection: 'row' }, sidebar: { width: 230, backgroundColor: '#172420', padding: 24 }, brand: { color: '#fff', fontSize: 20, fontWeight: '800', marginBottom: 42 }, brandAccent: { color: '#6bc7ad' }, company: { color: '#7e9c91', fontSize: 11, fontWeight: '700', letterSpacing: 1, marginBottom: 14 }, navItem: { padding: 12, borderRadius: 5, marginBottom: 4 }, navActive: { backgroundColor: '#2a4239' }, navText: { color: '#aebdb6', fontSize: 14 }, navTextActive: { color: '#fff', fontWeight: '700' }, signOut: { marginTop: 'auto', padding: 12 }, content: { maxWidth: 1120, width: '100%', alignSelf: 'center', padding: 32 }, heading: { color: '#172420', fontSize: 34, fontWeight: '700', marginTop: 8 }, date: { color: '#74817b', marginTop: 8 }, metrics: { flexDirection: 'row', gap: 14, marginTop: 28 }, metric: { backgroundColor: '#fff', borderRadius: 6, padding: 20, flex: 1, minWidth: 110 }, metricValue: { color: '#172420', fontSize: 28, fontWeight: '700' }, metricLabel: { color: '#74817b', marginTop: 5 }, section: { backgroundColor: '#fff', borderRadius: 6, marginTop: 18, padding: 22 }, sectionHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', gap: 20 }, sectionTitle: { color: '#172420', fontSize: 18, fontWeight: '700', marginBottom: 12 }, create: { flexDirection: 'row', gap: 8, flex: 1, maxWidth: 420 }, smallInput: { borderWidth: 1, borderColor: '#d8dfdb', borderRadius: 5, padding: 9, flex: 1 }, smallButton: { backgroundColor: '#167d6a', borderRadius: 5, paddingHorizontal: 14, justifyContent: 'center' }, row: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', borderTopWidth: 1, borderTopColor: '#edf0ed', paddingVertical: 14 }, rowTitle: { color: '#34433d', fontWeight: '600' }, meta: { color: '#74817b', fontSize: 12 }, good: { color: '#167d6a', fontWeight: '700' }, alert: { color: '#b36a2d', fontWeight: '700' }, empty: { color: '#74817b' } });
