export const fanixTheme = {
  colors: {
    primary: '#0E5CCB',
    primaryDark: '#0B2345',
    primaryLight: '#D9EAFF',
    background: '#F3F6FB',
    surface: '#FFFFFF',
    surfaceSecondary: '#EEF4FF',
    border: '#D5E0F0',
    textPrimary: '#122338',
    textSecondary: '#586C83',
    textMuted: '#7B8AA1',
    success: '#1E9E6A',
    warning: '#D98C1D',
    danger: '#D64E4E',
    info: '#2A6FE8',
    dark: '#0A172B',
    darkSurface: '#111F34',
    darkSurfaceSecondary: '#162B46',
    white: '#FFFFFF',
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 12,
    lg: 16,
    xl: 20,
    xxl: 24,
    huge: 32,
  },
  radius: {
    sm: 8,
    md: 12,
    lg: 16,
    xl: 20,
  },
  shadows: {
    sm: {
      shadowColor: '#0B2345',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.08,
      shadowRadius: 8,
      elevation: 2,
    },
    md: {
      shadowColor: '#0B2345',
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.12,
      shadowRadius: 12,
      elevation: 4,
    },
  },
  typography: {
    display: 36,
    h1: 30,
    h2: 24,
    h3: 20,
    body: 15,
    small: 12,
    label: 11,
  },
};

export default fanixTheme;
