import React, { useMemo, useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { FanixLogo } from '../components/branding/FanixLogo';
import { useFanixTheme } from '../theme/FanixThemeProvider';
import type { FanixTheme } from '../theme/fanixTheme';

const plans = [
  { id: 'starter', name: 'Starter', price: 499, description: 'Para negocios que empiezan a centralizar su operación.', limit: 3 },
  { id: 'professional', name: 'Professional', price: 1299, description: 'Para PyMEs que necesitan controlar más áreas.', limit: 6 },
  { id: 'business', name: 'Business', price: 2499, description: 'Para empresas con operación integral.', limit: 8 },
];
const modules = [
  ['crm','Clientes / CRM'], ['sales','Ventas'], ['inventory','Inventario'], ['purchases','Compras'],
  ['finance','Finanzas'], ['hr','Recursos humanos'], ['projects','Proyectos'], ['reports','Reportes'],
] as const;
type RegisterInput = { email: string; password: string; name: string; companyName: string; planId: string; billingCycle: 'monthly'|'annual'; modules: string[]; industry?: string; employeeCount?: number; country?: string; taxId?: string };

export function LandingPage({ onLogin, onRegister }: { onLogin: () => void; onRegister: (input: RegisterInput) => Promise<void> }) {
  const { theme } = useFanixTheme(); const styles = useMemo(() => createStyles(theme), [theme]);
  const [step, setStep] = useState<'home'|'register'>('home'); const [planId, setPlanId] = useState('professional');
  const [selected, setSelected] = useState<string[]>(['crm','sales','inventory','purchases','finance','reports']);
  const [form, setForm] = useState({ name:'', email:'', password:'', companyName:'', industry:'', taxId:'', employees:'' });
  const [error,setError]=useState(''); const [busy,setBusy]=useState(false);
  const plan=plans.find(p=>p.id===planId)!;
  function choosePlan(id:string){ const next=plans.find(p=>p.id===id)!; setPlanId(id); setSelected(prev=>prev.slice(0,next.limit)); }
  function toggle(id:string){ setSelected(prev=>prev.includes(id)?prev.filter(x=>x!==id):prev.length<plan.limit?[...prev,id]:prev); }
  async function submit(){ setError(''); if(!form.name.trim()||!form.companyName.trim()||!form.email.trim()||form.password.length<8){setError('Completa nombre, empresa, correo y una contraseña de al menos 8 caracteres.');return;} if(!selected.length){setError('Selecciona al menos un módulo.');return;} setBusy(true); try{await onRegister({name:form.name.trim(),email:form.email.trim().toLowerCase(),password:form.password,companyName:form.companyName.trim(),planId,billingCycle:'monthly',modules:selected,industry:form.industry.trim()||undefined,employeeCount:form.employees?Number(form.employees):undefined,country:'México',taxId:form.taxId.trim()||undefined});}catch(e){setError(e instanceof Error?e.message:'No se pudo crear la empresa.');}finally{setBusy(false);} }
  if(step==='register') return <ScrollView style={styles.page} contentContainerStyle={styles.container}><View style={styles.top}><FanixLogo size="login"/><Pressable onPress={()=>setStep('home')}><Text style={styles.link}>Volver</Text></Pressable></View><Text style={styles.h1}>Crea el espacio de tu empresa</Text><Text style={styles.lead}>14 días de prueba. Configura sólo los módulos que tu equipo necesita.</Text><View style={styles.grid}>{plans.map(p=><Pressable key={p.id} onPress={()=>choosePlan(p.id)} style={[styles.card,planId===p.id&&styles.selected]}><Text style={styles.cardTitle}>{p.name}</Text><Text style={styles.price}>$ {p.price} MXN / mes</Text><Text style={styles.muted}>{p.description}</Text></Pressable>)}</View><Text style={styles.h2}>Módulos ({selected.length}/{plan.limit})</Text><View style={styles.chips}>{modules.map(([id,label])=><Pressable key={id} onPress={()=>toggle(id)} style={[styles.chip,selected.includes(id)&&styles.chipSelected]}><Text style={styles.chipText}>{selected.includes(id)?'✓ ':''}{label}</Text></Pressable>)}</View><View style={styles.form}><TextInput style={styles.input} placeholder="Nombre del responsable" placeholderTextColor={theme.colors.inputPlaceholder} value={form.name} onChangeText={v=>setForm({...form,name:v})}/><TextInput style={styles.input} placeholder="Correo" autoCapitalize="none" keyboardType="email-address" placeholderTextColor={theme.colors.inputPlaceholder} value={form.email} onChangeText={v=>setForm({...form,email:v})}/><TextInput style={styles.input} placeholder="Contraseña (mínimo 8 caracteres)" secureTextEntry placeholderTextColor={theme.colors.inputPlaceholder} value={form.password} onChangeText={v=>setForm({...form,password:v})}/><TextInput style={styles.input} placeholder="Nombre de la empresa" placeholderTextColor={theme.colors.inputPlaceholder} value={form.companyName} onChangeText={v=>setForm({...form,companyName:v})}/><TextInput style={styles.input} placeholder="Industria (opcional)" placeholderTextColor={theme.colors.inputPlaceholder} value={form.industry} onChangeText={v=>setForm({...form,industry:v})}/><TextInput style={styles.input} placeholder="Número de empleados (opcional)" keyboardType="numeric" placeholderTextColor={theme.colors.inputPlaceholder} value={form.employees} onChangeText={v=>setForm({...form,employees:v.replace(/\D/g,'')})}/><TextInput style={styles.input} placeholder="RFC (opcional)" autoCapitalize="characters" placeholderTextColor={theme.colors.inputPlaceholder} value={form.taxId} onChangeText={v=>setForm({...form,taxId:v})}/></View>{error?<Text style={styles.error}>{error}</Text>:null}<Pressable disabled={busy} onPress={()=>void submit()} style={styles.primary}><Text style={styles.primaryText}>{busy?'Creando empresa…':'Crear empresa y comenzar prueba'}</Text></Pressable></ScrollView>;
  return <ScrollView style={styles.page} contentContainerStyle={styles.container}><View style={styles.top}><FanixLogo size="login"/><Pressable onPress={onLogin}><Text style={styles.link}>Iniciar sesión</Text></Pressable></View><View style={styles.hero}><Text style={styles.eyebrow}>ERP PARA EMPRESAS QUE QUIEREN CRECER</Text><Text style={styles.h1}>Toda tu operación en un solo lugar.</Text><Text style={styles.lead}>Fanix Global conecta ventas, clientes, inventario, compras, finanzas y equipos con una experiencia web y móvil consistente.</Text><View style={styles.actions}><Pressable onPress={()=>setStep('register')} style={styles.primary}><Text style={styles.primaryText}>Comenzar 14 días gratis</Text></Pressable><Pressable onPress={onLogin} style={styles.secondary}><Text style={styles.secondaryText}>Ya tengo una cuenta</Text></Pressable></View></View><Text style={styles.h2}>Elige cómo quieres trabajar</Text><View style={styles.grid}>{plans.map(p=><View key={p.id} style={styles.card}><Text style={styles.cardTitle}>{p.name}</Text><Text style={styles.price}>$ {p.price} MXN / mes</Text><Text style={styles.muted}>{p.description}</Text><Text style={styles.muted}>Hasta {p.limit} módulos.</Text><Pressable onPress={()=>{choosePlan(p.id);setStep('register')}} style={styles.secondary}><Text style={styles.secondaryText}>Elegir {p.name}</Text></Pressable></View>)}</View><Text style={styles.h2}>Módulos que crecen contigo</Text><View style={styles.chips}>{modules.map(([id,label])=><View key={id} style={styles.chip}><Text style={styles.chipText}>{label}</Text></View>)}</View></ScrollView>;
}
function createStyles(t:FanixTheme){return StyleSheet.create({page:{flex:1,backgroundColor:t.colors.background},container:{width:'100%',maxWidth:1180,alignSelf:'center',padding:24,gap:24},top:{flexDirection:'row',alignItems:'center',justifyContent:'space-between'},hero:{paddingVertical:56,maxWidth:820,gap:18},eyebrow:{fontWeight:'800',letterSpacing:1.4,color:t.colors.primary},h1:{fontSize:46,lineHeight:52,fontWeight:'900',color:t.colors.textPrimary},h2:{fontSize:26,fontWeight:'800',color:t.colors.textPrimary,marginTop:16},lead:{fontSize:19,lineHeight:29,color:t.colors.textMuted},actions:{flexDirection:'row',flexWrap:'wrap',gap:12},primary:{backgroundColor:t.colors.primary,paddingHorizontal:20,paddingVertical:14,borderRadius:12,alignItems:'center'},primaryText:{color:'#fff',fontWeight:'800'},secondary:{borderWidth:1,borderColor:t.colors.border,paddingHorizontal:18,paddingVertical:13,borderRadius:12,alignItems:'center'},secondaryText:{color:t.colors.textPrimary,fontWeight:'700'},link:{color:t.colors.primary,fontWeight:'800'},grid:{flexDirection:'row',flexWrap:'wrap',gap:16},card:{flexGrow:1,flexBasis:250,minWidth:240,padding:22,borderRadius:16,borderWidth:1,borderColor:t.colors.border,backgroundColor:t.colors.surface,gap:10},selected:{borderColor:t.colors.primary,borderWidth:2},cardTitle:{fontSize:20,fontWeight:'800',color:t.colors.textPrimary},price:{fontSize:24,fontWeight:'900',color:t.colors.primary},muted:{color:t.colors.textMuted,lineHeight:21},chips:{flexDirection:'row',flexWrap:'wrap',gap:10},chip:{borderWidth:1,borderColor:t.colors.border,borderRadius:999,paddingHorizontal:14,paddingVertical:10,backgroundColor:t.colors.surface},chipSelected:{borderColor:t.colors.primary},chipText:{color:t.colors.textPrimary,fontWeight:'600'},form:{gap:12,maxWidth:700},input:{borderWidth:1,borderColor:t.colors.border,borderRadius:10,padding:14,color:t.colors.textPrimary,backgroundColor:t.colors.surface},error:{color:t.colors.danger,fontWeight:'600'}})}
