import { Router } from 'express';
import { z } from 'zod';
import { db, id, now, type Customer, type Product } from './store.js';
import { asyncRoute, parseBody } from './http.js';
import { bomSchema, branchSchema, customerSchema, documentSchema, documentUploadSchema, employeeSchema, incidentSchema, loginSchema, movementSchema, paymentSchema, productionSchema, productSchema, projectSchema, purchaseSchema, quoteSchema, saleSchema, supplierSchema, taskSchema, transactionSchema, warehouseSchema } from './validation.js';
import { hashPassword, issueToken, requireAuth, requireRole, verifyPassword, type AuthRequest } from './auth.js';
import { readDocument, writeDocument } from './storage.js';

export const router = Router();
router.post('/auth/login', asyncRoute(async (req, res) => {
  const input = parseBody(loginSchema, req.body); const user = db.users.find(item => item.email === input.email.toLowerCase());
  if (!user || !(await verifyPassword(input.password, user.passwordHash))) return res.status(401).json({ error: { code: 'INVALID_CREDENTIALS', message: 'Invalid email or password' } });
  const membership = db.memberships.find(item => item.userId === user.id); if (!membership) return res.status(403).json({ error: { code: 'NO_MEMBERSHIP', message: 'No active company membership' } });
  res.json({ token: issueToken(user.id, membership.companyId, membership.role), user: { id: user.id, name: user.name, email: user.email }, company: db.companies.find(item => item.id === membership.companyId) });
}));
router.post('/auth/register', asyncRoute(async (req, res) => {
  const input = req.body as { email?: string; name?: string; password?: string; companyName?: string };
  if (!input.email || !input.name || !input.password || !input.companyName || input.password.length < 8) return res.status(400).json({ error: { code: 'VALIDATION_ERROR', message: 'name, email, companyName and password of 8+ characters are required' } });
  if (db.users.some(user => user.email === input.email!.toLowerCase())) return res.status(409).json({ error: { code: 'EMAIL_EXISTS', message: 'Email already registered' } });
  const user = { id: id(), email: input.email.toLowerCase(), name: input.name, passwordHash: await hashPassword(input.password), createdAt: now() };
  const company = { id: id(), name: input.companyName, currency: 'USD', enabledModules: ['crm', 'sales', 'inventory', 'reports'], createdAt: now() };
  db.users.push(user); db.companies.push(company); db.memberships.push({ userId: user.id, companyId: company.id, role: 'owner' });
  res.status(201).json({ token: issueToken(user.id, company.id, 'owner'), user: { id: user.id, name: user.name, email: user.email }, company });
}));

router.use(requireAuth);
router.get('/me', (req: AuthRequest, res) => res.json({ user: db.users.find(item => item.id === req.user!.id), company: db.companies.find(item => item.id === req.user!.companyId), role: req.user!.role }));
router.get('/customers', (req: AuthRequest, res) => { const search = String(req.query.search ?? '').toLowerCase(); res.json(db.customers.filter(item => item.companyId === req.user!.companyId && (!search || item.name.toLowerCase().includes(search) || item.email?.toLowerCase().includes(search)))); });
router.post('/customers', requireRole('owner', 'admin', 'sales'), (req: AuthRequest, res) => { const input = parseBody(customerSchema, req.body); const customer: Customer = { id: id(), companyId: req.user!.companyId, ...input, createdAt: now() }; db.customers.push(customer); db.audits.push({ id: id(), companyId: req.user!.companyId, userId: req.user!.id, action: 'create', entity: 'customer', entityId: customer.id, createdAt: now() }); res.status(201).json(customer); });
router.get('/products', (req: AuthRequest, res) => res.json(db.products.filter(item => item.companyId === req.user!.companyId).map(product => ({ ...product, stock: db.movements.filter(move => move.companyId === product.companyId && move.productId === product.id).reduce((sum, move) => sum + (move.type === 'out' ? -move.quantity : move.quantity), 0) }))));
router.post('/products', requireRole('owner', 'admin', 'inventory'), (req: AuthRequest, res) => { const input = parseBody(productSchema, req.body); const product: Product = { id: id(), companyId: req.user!.companyId, ...input, createdAt: now() }; db.products.push(product); res.status(201).json(product); });
router.get('/suppliers', (req: AuthRequest, res) => res.json(db.suppliers.filter(item => item.companyId === req.user!.companyId)));
router.post('/suppliers', requireRole('owner', 'admin'), (req: AuthRequest, res) => { const input = parseBody(supplierSchema, req.body); const supplier = { id: id(), companyId: req.user!.companyId, ...input, status: 'active' as const, createdAt: now() }; db.suppliers.push(supplier); res.status(201).json(supplier); });
router.get('/purchases', (req: AuthRequest, res) => res.json(db.purchases.filter(item => item.companyId === req.user!.companyId)));
router.post('/purchases', requireRole('owner', 'admin'), (req: AuthRequest, res) => { const key = req.header('idempotency-key'); if (!key) return res.status(400).json({ error: { code: 'IDEMPOTENCY_KEY_REQUIRED', message: 'Idempotency-Key header is required' } }); const previous = db.purchases.find(item => item.companyId === req.user!.companyId && item.idempotencyKey === key); if (previous) return res.json(previous); const input = parseBody(purchaseSchema, req.body); const supplier = db.suppliers.find(item => item.id === input.supplierId && item.companyId === req.user!.companyId); if (!supplier) return res.status(404).json({ error: { code: 'SUPPLIER_NOT_FOUND', message: 'Supplier not found' } }); const items = input.items.map(item => { const product = db.products.find(candidate => candidate.id === item.productId && candidate.companyId === req.user!.companyId); if (!product) throw new Error('PRODUCT_NOT_FOUND'); return { productId: product.id, quantity: item.quantity, unitCost: item.unitCost ?? product.cost }; }); const purchase = { id: id(), companyId: req.user!.companyId, supplierId: input.supplierId, items, total: items.reduce((sum, item) => sum + item.quantity * item.unitCost, 0), status: 'draft' as const, idempotencyKey: key, createdAt: now() }; db.purchases.push(purchase); res.status(201).json(purchase); });
router.post('/purchases/:purchaseId/approve', requireRole('owner', 'admin'), (req: AuthRequest, res) => { const purchase = db.purchases.find(item => item.id === req.params.purchaseId && item.companyId === req.user!.companyId); if (!purchase) return res.status(404).json({ error: { code: 'PURCHASE_NOT_FOUND', message: 'Purchase not found' } }); if (purchase.status !== 'draft') return res.status(409).json({ error: { code: 'INVALID_STATE', message: 'Only draft purchases can be approved' } }); purchase.status = 'approved'; res.json(purchase); });
router.post('/purchases/:purchaseId/reject', requireRole('owner', 'admin'), (req: AuthRequest, res) => { const purchase = db.purchases.find(item => item.id === req.params.purchaseId && item.companyId === req.user!.companyId); if (!purchase) return res.status(404).json({ error: { code: 'PURCHASE_NOT_FOUND', message: 'Purchase not found' } }); if (purchase.status !== 'draft') return res.status(409).json({ error: { code: 'INVALID_STATE', message: 'Only draft purchases can be rejected' } }); purchase.status = 'rejected'; res.json(purchase); });
router.post('/purchases/:purchaseId/receive', requireRole('owner', 'admin', 'inventory'), (req: AuthRequest, res) => { const purchase = db.purchases.find(item => item.id === req.params.purchaseId && item.companyId === req.user!.companyId); if (!purchase) return res.status(404).json({ error: { code: 'PURCHASE_NOT_FOUND', message: 'Purchase not found' } }); if (purchase.status !== 'approved') return res.status(409).json({ error: { code: 'INVALID_STATE', message: 'Purchase must be approved before receipt' } }); purchase.items.forEach(item => db.movements.push({ id: id(), companyId: purchase.companyId, productId: item.productId, type: 'in', quantity: item.quantity, reference: purchase.id, createdAt: now() })); purchase.status = 'received'; res.json(purchase); });
router.post('/inventory/movements', requireRole('owner', 'admin', 'inventory'), (req: AuthRequest, res) => { const input = parseBody(movementSchema, req.body); const product = db.products.find(item => item.id === input.productId && item.companyId === req.user!.companyId); if (!product) return res.status(404).json({ error: { code: 'PRODUCT_NOT_FOUND', message: 'Product not found' } }); const stock = db.movements.filter(move => move.companyId === product.companyId && move.productId === product.id).reduce((sum, move) => sum + (move.type === 'out' ? -move.quantity : move.quantity), 0); if (input.type === 'out' && input.quantity > stock) return res.status(409).json({ error: { code: 'INSUFFICIENT_STOCK', message: 'Insufficient stock' } }); const movement = { id: id(), companyId: req.user!.companyId, ...input, createdAt: now() }; db.movements.push(movement); res.status(201).json({ movement, stock: stock + (input.type === 'out' ? -input.quantity : input.quantity) }); });
router.post('/sales', requireRole('owner', 'admin', 'sales'), (req: AuthRequest, res) => { const key = req.header('idempotency-key'); if (!key) return res.status(400).json({ error: { code: 'IDEMPOTENCY_KEY_REQUIRED', message: 'Idempotency-Key header is required' } }); const previous = db.sales.find(sale => sale.companyId === req.user!.companyId && sale.idempotencyKey === key); if (previous) return res.status(200).json(previous); const input = parseBody(saleSchema, req.body); const customer = db.customers.find(item => item.id === input.customerId && item.companyId === req.user!.companyId); if (!customer) return res.status(404).json({ error: { code: 'CUSTOMER_NOT_FOUND', message: 'Customer not found' } }); const items = input.items.map(item => { const product = db.products.find(candidate => candidate.id === item.productId && candidate.companyId === req.user!.companyId); if (!product) throw new Error('PRODUCT_NOT_FOUND'); return { productId: product.id, quantity: item.quantity, unitPrice: item.unitPrice ?? product.price }; }); for (const item of items) { const stock = db.movements.filter(move => move.companyId === req.user!.companyId && move.productId === item.productId).reduce((sum, move) => sum + (move.type === 'out' ? -move.quantity : move.quantity), 0); if (item.quantity > stock) return res.status(409).json({ error: { code: 'INSUFFICIENT_STOCK', message: 'Insufficient stock' } }); } const sale = { id: id(), companyId: req.user!.companyId, customerId: input.customerId, items, total: items.reduce((sum, item) => sum + item.quantity * item.unitPrice, 0), status: 'confirmed' as const, idempotencyKey: key, createdAt: now() }; db.sales.push(sale); items.forEach(item => db.movements.push({ id: id(), companyId: sale.companyId, productId: item.productId, type: 'out', quantity: item.quantity, reference: sale.id, createdAt: now() })); db.audits.push({ id: id(), companyId: sale.companyId, userId: req.user!.id, action: 'confirm', entity: 'sale', entityId: sale.id, createdAt: now() }); res.status(201).json(sale); });
router.get('/quotes', requireRole('owner', 'admin', 'sales'), (req: AuthRequest, res) => res.json(db.quotes.filter(item => item.companyId === req.user!.companyId)));
router.post('/quotes', requireRole('owner', 'admin', 'sales'), (req: AuthRequest, res) => { const input = parseBody(quoteSchema, req.body); if (!db.customers.some(item => item.id === input.customerId && item.companyId === req.user!.companyId)) return res.status(404).json({ error: { code: 'CUSTOMER_NOT_FOUND', message: 'Customer not found' } }); if (input.items.some(item => !db.products.some(product => product.id === item.productId && product.companyId === req.user!.companyId))) return res.status(404).json({ error: { code: 'PRODUCT_NOT_FOUND', message: 'Product not found' } }); const subtotal = input.items.reduce((sum, item) => sum + item.quantity * item.unitPrice, 0); const quote = { id: id(), companyId: req.user!.companyId, customerId: input.customerId, items: input.items, subtotal, tax: subtotal * input.taxRate, total: subtotal * (1 + input.taxRate), status: 'draft' as const, createdAt: now() }; db.quotes.push(quote); res.status(201).json(quote); });
router.patch('/quotes/:quoteId/status', requireRole('owner', 'admin', 'sales'), (req: AuthRequest, res) => { const quote = db.quotes.find(item => item.id === req.params.quoteId && item.companyId === req.user!.companyId); if (!quote) return res.status(404).json({ error: { code: 'QUOTE_NOT_FOUND', message: 'Quote not found' } }); const status = z.enum(['draft', 'sent', 'accepted', 'rejected', 'expired']).parse((req.body as { status?: string }).status); if (quote.status === 'expired' || (quote.status === 'rejected' && status !== 'draft')) return res.status(409).json({ error: { code: 'INVALID_STATE', message: 'Quote cannot transition from its current state' } }); quote.status = status; res.json(quote); });
router.get('/payments', requireRole('owner', 'admin'), (req: AuthRequest, res) => res.json(db.payments.filter(item => item.companyId === req.user!.companyId)));
router.post('/payments', requireRole('owner', 'admin', 'sales'), (req: AuthRequest, res) => { const key = req.header('idempotency-key'); if (!key) return res.status(400).json({ error: { code: 'IDEMPOTENCY_KEY_REQUIRED', message: 'Idempotency-Key header is required' } }); const previous = db.payments.find(item => item.companyId === req.user!.companyId && item.idempotencyKey === key); if (previous) return res.json(previous); const input = parseBody(paymentSchema, req.body); const validReference = input.type === 'sale' ? db.sales.some(item => item.id === input.referenceId && item.companyId === req.user!.companyId) : input.type === 'purchase' ? db.purchases.some(item => item.id === input.referenceId && item.companyId === req.user!.companyId) : db.financialTransactions.some(item => item.id === input.referenceId && item.companyId === req.user!.companyId); if (!validReference) return res.status(404).json({ error: { code: 'REFERENCE_NOT_FOUND', message: 'Payment reference not found' } }); const payment = { id: id(), companyId: req.user!.companyId, ...input, status: 'completed' as const, idempotencyKey: key, createdAt: now() }; db.payments.push(payment); res.status(201).json(payment); });
router.get('/dashboard', (req: AuthRequest, res) => { const companyId = req.user!.companyId; const products = db.products.filter(item => item.companyId === companyId); const inventory = products.map(product => ({ product, stock: db.movements.filter(move => move.companyId === companyId && move.productId === product.id).reduce((sum, move) => sum + (move.type === 'out' ? -move.quantity : move.quantity), 0) })).filter(item => item.stock <= item.product.stockMinimum); const unreadNotifications = db.notifications.filter(item => item.companyId === companyId && (!item.userId || item.userId === req.user!.id) && !item.readAt); res.json({ counts: { customers: db.customers.filter(item => item.companyId === companyId).length, products: products.length, sales: db.sales.filter(item => item.companyId === companyId).length, purchases: db.purchases.filter(item => item.companyId === companyId).length, unreadNotifications: unreadNotifications.length }, lowStock: inventory, recentActivity: db.audits.filter(item => item.companyId === companyId).slice(-10).reverse(), enabledModules: db.companies.find(item => item.id === companyId)?.enabledModules ?? [] }); });
router.get('/audit-logs', requireRole('owner', 'admin'), (req: AuthRequest, res) => res.json(db.audits.filter(item => item.companyId === req.user!.companyId)));
router.get('/reports/sales.csv', requireRole('owner', 'admin', 'sales'), (req: AuthRequest, res) => { const rows = db.sales.filter(item => item.companyId === req.user!.companyId); res.type('text/csv').send(['id,customerId,total,status,createdAt', ...rows.map(item => `${item.id},${item.customerId},${item.total},${item.status},${item.createdAt}`)].join('\n')); });

router.get('/employees', requireRole('owner', 'admin'), (req: AuthRequest, res) => res.json(db.employees.filter(item => item.companyId === req.user!.companyId)));
router.post('/employees', requireRole('owner', 'admin'), (req: AuthRequest, res) => { const input = parseBody(employeeSchema, req.body); const employee = { id: id(), companyId: req.user!.companyId, ...input, createdAt: now() }; db.employees.push(employee); db.audits.push({ id: id(), companyId: employee.companyId, userId: req.user!.id, action: 'create', entity: 'employee', entityId: employee.id, createdAt: now() }); res.status(201).json(employee); });
router.patch('/employees/:employeeId', requireRole('owner', 'admin'), (req: AuthRequest, res) => { const employee = db.employees.find(item => item.id === req.params.employeeId && item.companyId === req.user!.companyId); if (!employee) return res.status(404).json({ error: { code: 'EMPLOYEE_NOT_FOUND', message: 'Employee not found' } }); const input = parseBody(employeeSchema.partial(), req.body); Object.assign(employee, input); res.json(employee); });

router.get('/projects', (req: AuthRequest, res) => res.json(db.projects.filter(item => item.companyId === req.user!.companyId)));
router.post('/projects', requireRole('owner', 'admin', 'sales'), (req: AuthRequest, res) => { const input = parseBody(projectSchema, req.body); if (!db.users.some(user => user.id === input.ownerId && db.memberships.some(member => member.userId === user.id && member.companyId === req.user!.companyId))) return res.status(400).json({ error: { code: 'OWNER_NOT_MEMBER', message: 'Project owner must belong to the company' } }); const project = { id: id(), companyId: req.user!.companyId, ...input, status: 'planned' as const, createdAt: now() }; db.projects.push(project); res.status(201).json(project); });
router.get('/projects/:projectId/tasks', (req: AuthRequest, res) => { const project = db.projects.find(item => item.id === req.params.projectId && item.companyId === req.user!.companyId); if (!project) return res.status(404).json({ error: { code: 'PROJECT_NOT_FOUND', message: 'Project not found' } }); res.json(db.tasks.filter(item => item.projectId === project.id && item.companyId === req.user!.companyId)); });
router.post('/projects/:projectId/tasks', requireRole('owner', 'admin', 'sales'), (req: AuthRequest, res) => { const project = db.projects.find(item => item.id === req.params.projectId && item.companyId === req.user!.companyId); if (!project) return res.status(404).json({ error: { code: 'PROJECT_NOT_FOUND', message: 'Project not found' } }); const input = parseBody(taskSchema, req.body); const task = { id: id(), companyId: project.companyId, projectId: project.id, ...input, status: 'todo' as const, createdAt: now() }; db.tasks.push(task); res.status(201).json(task); });
router.patch('/projects/:projectId/status', requireRole('owner', 'admin', 'sales'), (req: AuthRequest, res) => { const project = db.projects.find(item => item.id === req.params.projectId && item.companyId === req.user!.companyId); const status = z.enum(['planned', 'active', 'closed']).parse((req.body as { status?: string }).status); if (!project) return res.status(404).json({ error: { code: 'PROJECT_NOT_FOUND', message: 'Project not found' } }); project.status = status; res.json(project); });

router.get('/finance/transactions', requireRole('owner', 'admin'), (req: AuthRequest, res) => res.json(db.financialTransactions.filter(item => item.companyId === req.user!.companyId)));
router.post('/finance/transactions', requireRole('owner', 'admin'), (req: AuthRequest, res) => { const input = parseBody(transactionSchema, req.body); const transaction = { id: id(), companyId: req.user!.companyId, ...input, createdAt: now() }; db.financialTransactions.push(transaction); res.status(201).json(transaction); });
router.post('/finance/transactions/:transactionId/pay', requireRole('owner', 'admin'), (req: AuthRequest, res) => { const transaction = db.financialTransactions.find(item => item.id === req.params.transactionId && item.companyId === req.user!.companyId); if (!transaction) return res.status(404).json({ error: { code: 'TRANSACTION_NOT_FOUND', message: 'Transaction not found' } }); transaction.status = 'paid'; res.json(transaction); });

router.get('/notifications', (req: AuthRequest, res) => res.json(db.notifications.filter(item => item.companyId === req.user!.companyId && (!item.userId || item.userId === req.user!.id))));
router.post('/notifications/:notificationId/read', (req: AuthRequest, res) => { const notification = db.notifications.find(item => item.id === req.params.notificationId && item.companyId === req.user!.companyId && (!item.userId || item.userId === req.user!.id)); if (!notification) return res.status(404).json({ error: { code: 'NOTIFICATION_NOT_FOUND', message: 'Notification not found' } }); notification.readAt = now(); res.json(notification); });
router.get('/documents', (req: AuthRequest, res) => res.json(db.documents.filter(item => item.companyId === req.user!.companyId)));
router.post('/documents', requireRole('owner', 'admin'), (req: AuthRequest, res) => { const input = parseBody(documentSchema, req.body); const document = { id: id(), companyId: req.user!.companyId, ...input, createdBy: req.user!.id, createdAt: now() }; db.documents.push(document); db.audits.push({ id: id(), companyId: document.companyId, userId: req.user!.id, action: 'create', entity: 'document', entityId: document.id, createdAt: now() }); res.status(201).json(document); });
router.post('/documents/upload', requireRole('owner', 'admin'), asyncRoute(async (req, res) => { const input = parseBody(documentUploadSchema, req.body); const stored = await writeDocument(input.contentBase64, input.extension); const auth = req as AuthRequest; const document = { id: id(), companyId: auth.user!.companyId, name: input.name, category: input.category, storageKey: stored.key, entity: input.entity, entityId: input.entityId, createdBy: auth.user!.id, createdAt: now() }; db.documents.push(document); db.audits.push({ id: id(), companyId: document.companyId, userId: document.createdBy, action: 'upload', entity: 'document', entityId: document.id, createdAt: now() }); res.status(201).json({ ...document, bytes: stored.bytes }); }));
router.get('/documents/:documentId', requireRole('owner', 'admin'), (req: AuthRequest, res) => { const document = db.documents.find(item => item.id === req.params.documentId && item.companyId === req.user!.companyId); if (!document) return res.status(404).json({ error: { code: 'DOCUMENT_NOT_FOUND', message: 'Document not found' } }); res.json(document); });
router.get('/documents/:documentId/download', requireRole('owner', 'admin'), asyncRoute(async (req, res) => { const auth = req as AuthRequest; const document = db.documents.find(item => item.id === req.params.documentId && item.companyId === auth.user!.companyId); if (!document) return res.status(404).json({ error: { code: 'DOCUMENT_NOT_FOUND', message: 'Document not found' } }); try { const content = await readDocument(document.storageKey); res.type('application/octet-stream').send(content); } catch { res.status(404).json({ error: { code: 'FILE_NOT_FOUND', message: 'Document file not found' } }); } }));
router.get('/incidents', (req: AuthRequest, res) => res.json(db.incidents.filter(item => item.companyId === req.user!.companyId)));
router.post('/incidents', (req: AuthRequest, res) => { const input = parseBody(incidentSchema, req.body); const incident = { id: id(), companyId: req.user!.companyId, ...input, status: 'open' as const, createdBy: req.user!.id, createdAt: now() }; db.incidents.push(incident); res.status(201).json(incident); });
router.patch('/incidents/:incidentId/resolve', requireRole('owner', 'admin'), (req: AuthRequest, res) => { const incident = db.incidents.find(item => item.id === req.params.incidentId && item.companyId === req.user!.companyId); if (!incident) return res.status(404).json({ error: { code: 'INCIDENT_NOT_FOUND', message: 'Incident not found' } }); incident.status = 'resolved'; res.json(incident); });
router.get('/production/orders', requireRole('owner', 'admin', 'inventory'), (req: AuthRequest, res) => res.json(db.productionOrders.filter(item => item.companyId === req.user!.companyId)));
router.post('/production/orders', requireRole('owner', 'admin', 'inventory'), (req: AuthRequest, res) => { const company = db.companies.find(item => item.id === req.user!.companyId); if (!company?.enabledModules.includes('production')) return res.status(409).json({ error: { code: 'MODULE_DISABLED', message: 'Production module is disabled' } }); const input = parseBody(productionSchema, req.body); if (!db.products.some(item => item.id === input.productId && item.companyId === req.user!.companyId)) return res.status(404).json({ error: { code: 'PRODUCT_NOT_FOUND', message: 'Product not found' } }); const order = { id: id(), companyId: req.user!.companyId, ...input, status: 'planned' as const, createdAt: now() }; db.productionOrders.push(order); res.status(201).json(order); });
router.post('/production/boms', requireRole('owner', 'admin', 'inventory'), (req: AuthRequest, res) => { const input = parseBody(bomSchema, req.body); if (!db.products.some(item => item.id === input.productId && item.companyId === req.user!.companyId)) return res.status(404).json({ error: { code: 'PRODUCT_NOT_FOUND', message: 'Finished product not found' } }); if (input.components.some(component => !db.products.some(item => item.id === component.productId && item.companyId === req.user!.companyId))) return res.status(404).json({ error: { code: 'COMPONENT_NOT_FOUND', message: 'BOM component not found' } }); const existing = db.billsOfMaterial.find(item => item.productId === input.productId && item.companyId === req.user!.companyId); if (existing) existing.components = input.components; else db.billsOfMaterial.push({ id: id(), companyId: req.user!.companyId, ...input, createdAt: now() }); res.status(201).json(db.billsOfMaterial.find(item => item.productId === input.productId && item.companyId === req.user!.companyId)); });
router.post('/production/orders/:orderId/start', requireRole('owner', 'admin', 'inventory'), (req: AuthRequest, res) => { const order = db.productionOrders.find(item => item.id === req.params.orderId && item.companyId === req.user!.companyId); if (!order) return res.status(404).json({ error: { code: 'ORDER_NOT_FOUND', message: 'Production order not found' } }); if (order.status !== 'planned') return res.status(409).json({ error: { code: 'INVALID_STATE', message: 'Only planned orders can start' } }); order.status = 'in_progress'; res.json(order); });
router.post('/production/orders/:orderId/complete', requireRole('owner', 'admin', 'inventory'), (req: AuthRequest, res) => { const order = db.productionOrders.find(item => item.id === req.params.orderId && item.companyId === req.user!.companyId); if (!order) return res.status(404).json({ error: { code: 'ORDER_NOT_FOUND', message: 'Production order not found' } }); if (order.status !== 'in_progress') return res.status(409).json({ error: { code: 'INVALID_STATE', message: 'Order must be in progress before completion' } }); const bom = db.billsOfMaterial.find(item => item.productId === order.productId && item.companyId === req.user!.companyId); if (!bom) return res.status(409).json({ error: { code: 'BOM_REQUIRED', message: 'A bill of materials is required' } }); const stockOf = (productId: string) => db.movements.filter(move => move.companyId === req.user!.companyId && move.productId === productId).reduce((sum, move) => sum + (move.type === 'out' ? -move.quantity : move.quantity), 0); const requirements = bom.components.map(component => ({ ...component, required: component.quantity * order.quantity, stock: stockOf(component.productId) })); const shortage = requirements.find(item => item.required > item.stock); if (shortage) return res.status(409).json({ error: { code: 'INSUFFICIENT_COMPONENT_STOCK', message: `Insufficient stock for component ${shortage.productId}` } }); requirements.forEach(item => db.movements.push({ id: id(), companyId: order.companyId, productId: item.productId, type: 'out', quantity: item.required, reference: order.id, createdAt: now() })); db.movements.push({ id: id(), companyId: order.companyId, productId: order.productId, type: 'in', quantity: order.quantity, reference: order.id, createdAt: now() }); order.status = 'completed'; db.audits.push({ id: id(), companyId: order.companyId, userId: req.user!.id, action: 'complete', entity: 'production_order', entityId: order.id, createdAt: now() }); res.json(order); });

router.get('/company', (req: AuthRequest, res) => res.json(db.companies.find(item => item.id === req.user!.companyId)));
router.patch('/company/modules', requireRole('owner', 'admin'), (req: AuthRequest, res) => { const company = db.companies.find(item => item.id === req.user!.companyId); const modules = z.array(z.string().trim().min(1)).max(50).parse((req.body as { enabledModules?: string[] }).enabledModules); if (!company) return res.status(404).json({ error: { code: 'COMPANY_NOT_FOUND', message: 'Company not found' } }); company.enabledModules = [...new Set(modules)]; res.json(company); });
router.get('/branches', (req: AuthRequest, res) => res.json(db.branches.filter(item => item.companyId === req.user!.companyId)));
router.post('/branches', requireRole('owner', 'admin'), (req: AuthRequest, res) => { const input = parseBody(branchSchema, req.body); const branch = { id: id(), companyId: req.user!.companyId, ...input, createdAt: now() }; db.branches.push(branch); res.status(201).json(branch); });
router.patch('/branches/:branchId', requireRole('owner', 'admin'), (req: AuthRequest, res) => { const branch = db.branches.find(item => item.id === req.params.branchId && item.companyId === req.user!.companyId); if (!branch) return res.status(404).json({ error: { code: 'BRANCH_NOT_FOUND', message: 'Branch not found' } }); Object.assign(branch, parseBody(branchSchema.partial(), req.body)); res.json(branch); });
router.get('/warehouses', (req: AuthRequest, res) => res.json(db.warehouses.filter(item => item.companyId === req.user!.companyId)));
router.post('/warehouses', requireRole('owner', 'admin', 'inventory'), (req: AuthRequest, res) => { const input = parseBody(warehouseSchema, req.body); if (input.branchId && !db.branches.some(item => item.id === input.branchId && item.companyId === req.user!.companyId)) return res.status(404).json({ error: { code: 'BRANCH_NOT_FOUND', message: 'Branch not found' } }); const warehouse = { id: id(), companyId: req.user!.companyId, ...input, createdAt: now() }; db.warehouses.push(warehouse); res.status(201).json(warehouse); });
