import test from 'node:test';
import assert from 'node:assert/strict';
import { createApp } from './app.js';
import { db } from './store.js';

async function runningApp() { const server = createApp().listen(0); await new Promise<void>(resolve => server.once('listening', () => resolve())); return server; }
test('health endpoint is public', async () => { const server = await runningApp(); const response = await fetch(`http://localhost:${(server.address() as { port: number }).port}/api/v1/health`); assert.equal(response.status, 200); server.close(); });
test('protected data rejects missing token', async () => { const server = await runningApp(); const response = await fetch(`http://localhost:${(server.address() as { port: number }).port}/api/v1/customers`); assert.equal(response.status, 401); server.close(); });
test('login returns a company-scoped token', async () => { if (!db.users.length) await (await import('./store.js')).seedOwner(); const server = await runningApp(); const response = await fetch(`http://localhost:${(server.address() as { port: number }).port}/api/v1/auth/login`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ email: 'admin@demo.local', password: 'Admin123!' }) }); const body = await response.json() as { token: string; company: { id: string } }; assert.equal(response.status, 200); assert.ok(body.token); assert.ok(body.company.id); server.close(); });
test('company data is isolated and critical inventory flow is idempotent', async () => {
	if (!db.users.length) await (await import('./store.js')).seedOwner();
	const server = await runningApp(); const base = `http://localhost:${(server.address() as { port: number }).port}/api/v1`;
	const login = await fetch(`${base}/auth/login`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ email: 'admin@demo.local', password: 'Admin123!' }) });
	const owner = await login.json() as { token: string; company: { id: string } }; const auth = { Authorization: `Bearer ${owner.token}`, 'Content-Type': 'application/json' };
	const second = await fetch(`${base}/auth/register`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ email: `other-${Date.now()}@demo.local`, name: 'Otra empresa', password: 'Admin123!', companyName: 'Otra empresa' }) });
	const other = await second.json() as { token: string }; const otherCustomers = await fetch(`${base}/customers`, { headers: { Authorization: `Bearer ${other.token}` } }); assert.deepEqual(await otherCustomers.json(), []);
	const customerResponse = await fetch(`${base}/customers`, { method: 'POST', headers: auth, body: JSON.stringify({ name: 'Cliente flujo' }) }); const customer = await customerResponse.json() as { id: string };
	const productResponse = await fetch(`${base}/products`, { method: 'POST', headers: auth, body: JSON.stringify({ sku: `SKU-${Date.now()}`, name: 'Producto flujo', price: 10, cost: 5, stockMinimum: 1 }) }); const product = await productResponse.json() as { id: string };
	const supplierResponse = await fetch(`${base}/suppliers`, { method: 'POST', headers: auth, body: JSON.stringify({ name: 'Proveedor flujo' }) }); const supplier = await supplierResponse.json() as { id: string };
	const purchaseResponse = await fetch(`${base}/purchases`, { method: 'POST', headers: { ...auth, 'Idempotency-Key': `purchase-${Date.now()}` }, body: JSON.stringify({ supplierId: supplier.id, items: [{ productId: product.id, quantity: 3 }] }) }); const purchase = await purchaseResponse.json() as { id: string };
	await fetch(`${base}/purchases/${purchase.id}/approve`, { method: 'POST', headers: auth }); const received = await fetch(`${base}/purchases/${purchase.id}/receive`, { method: 'POST', headers: auth }); assert.equal(received.status, 200);
	const key = `sale-${Date.now()}`; const saleBody = JSON.stringify({ customerId: customer.id, items: [{ productId: product.id, quantity: 2 }] }); const firstSale = await fetch(`${base}/sales`, { method: 'POST', headers: { ...auth, 'Idempotency-Key': key }, body: saleBody }); const first = await firstSale.json() as { id: string };
	const retrySale = await fetch(`${base}/sales`, { method: 'POST', headers: { ...auth, 'Idempotency-Key': key }, body: saleBody }); const retry = await retrySale.json() as { id: string }; assert.equal(retrySale.status, 200); assert.equal(retry.id, first.id);
	const rejected = await fetch(`${base}/sales`, { method: 'POST', headers: { ...auth, 'Idempotency-Key': `over-${Date.now()}` }, body: JSON.stringify({ customerId: customer.id, items: [{ productId: product.id, quantity: 2 }] }) }); assert.equal(rejected.status, 409);
	server.close();
});
test('quotes, payments, documents and production are integrated', async () => {
	const server = await runningApp(); const base = `http://localhost:${(server.address() as { port: number }).port}/api/v1`;
	const login = await fetch(`${base}/auth/login`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ email: 'admin@demo.local', password: 'Admin123!' }) });
	const owner = await login.json() as { token: string; company: { id: string } }; const auth = { Authorization: `Bearer ${owner.token}`, 'Content-Type': 'application/json' };
	const customer = db.customers.find(item => item.companyId === owner.company.id); const product = db.products.find(item => item.companyId === owner.company.id); assert.ok(customer); assert.ok(product);
	const quoteResponse = await fetch(`${base}/quotes`, { method: 'POST', headers: auth, body: JSON.stringify({ customerId: customer.id, items: [{ productId: product.id, quantity: 1, unitPrice: 10 }], taxRate: 0.1 }) }); assert.equal(quoteResponse.status, 201);
	const sale = db.sales.find(item => item.companyId === owner.company.id); assert.ok(sale); const paymentKey = `payment-${Date.now()}`; const paymentBody = JSON.stringify({ type: 'sale', referenceId: sale.id, amount: sale.total, method: 'card' }); const paymentResponse = await fetch(`${base}/payments`, { method: 'POST', headers: { ...auth, 'Idempotency-Key': paymentKey }, body: paymentBody }); assert.equal(paymentResponse.status, 201); const paymentRetry = await fetch(`${base}/payments`, { method: 'POST', headers: { ...auth, 'Idempotency-Key': paymentKey }, body: paymentBody }); assert.equal(paymentRetry.status, 200);
	const upload = await fetch(`${base}/documents/upload`, { method: 'POST', headers: auth, body: JSON.stringify({ name: 'prueba.txt', category: 'qa', extension: 'txt', contentBase64: Buffer.from('ERP document').toString('base64') }) }); assert.equal(upload.status, 201); const document = await upload.json() as { id: string }; const download = await fetch(`${base}/documents/${document.id}/download`, { headers: { Authorization: `Bearer ${owner.token}` } }); assert.equal(download.status, 200); assert.equal(await download.text(), 'ERP document');
	await fetch(`${base}/company/modules`, { method: 'PATCH', headers: auth, body: JSON.stringify({ enabledModules: ['production', 'inventory', 'sales'] }) }); const rawResponse = await fetch(`${base}/products`, { method: 'POST', headers: auth, body: JSON.stringify({ sku: `RAW-${Date.now()}`, name: 'Materia prima QA', price: 1, cost: 1 }) }); const raw = await rawResponse.json() as { id: string }; const finishedResponse = await fetch(`${base}/products`, { method: 'POST', headers: auth, body: JSON.stringify({ sku: `FIN-${Date.now()}`, name: 'Producto terminado QA', price: 4, cost: 2 }) }); const finished = await finishedResponse.json() as { id: string }; await fetch(`${base}/inventory/movements`, { method: 'POST', headers: auth, body: JSON.stringify({ productId: raw.id, type: 'in', quantity: 2 }) }); await fetch(`${base}/production/boms`, { method: 'POST', headers: auth, body: JSON.stringify({ productId: finished.id, components: [{ productId: raw.id, quantity: 1 }] }) }); const orderResponse = await fetch(`${base}/production/orders`, { method: 'POST', headers: auth, body: JSON.stringify({ productId: finished.id, quantity: 2 }) }); const order = await orderResponse.json() as { id: string }; await fetch(`${base}/production/orders/${order.id}/start`, { method: 'POST', headers: auth }); const completed = await fetch(`${base}/production/orders/${order.id}/complete`, { method: 'POST', headers: auth }); assert.equal(completed.status, 200);
	server.close();
});
