import { z } from 'zod';

const safeName = z.string().trim().min(2).max(120).regex(/^[\p{L}\p{M}0-9 .,'&()\-]+$/u, 'Contains invalid characters');
const safeShortText = (max: number) => z.string().trim().max(max).regex(/^[\p{L}\p{M}0-9 .,'&()_\-/#]*$/u, 'Contains invalid characters');
const phone = z.string().trim().min(7).max(20).regex(/^\+?[0-9 ()\-]+$/, 'Invalid phone number');
const sku = z.string().trim().min(1).max(40).regex(/^[A-Za-z0-9._\-]+$/, 'Invalid SKU');
const isoDate = z.string().regex(/^\d{4}-\d{2}-\d{2}$/, 'Use YYYY-MM-DD').refine(value => !Number.isNaN(Date.parse(`${value}T00:00:00Z`)), 'Invalid date');
const money = z.number().finite().nonnegative().max(999999999.99);
const positiveMoney = z.number().finite().positive().max(999999999.99);
const uniqueProducts = <T extends { productId: string }>(items: T[]) => new Set(items.map(item => item.productId)).size === items.length;

export const loginSchema = z.object({ email: z.string().trim().email().max(254), password: z.string().min(8).max(72) });
export const customerSchema = z.object({ name: safeName, email: z.string().trim().email().max(254).optional(), phone: phone.optional(), classification: safeShortText(40).optional() });
export const productSchema = z.object({ sku, name: safeName, price: money, cost: money, stockMinimum: z.number().int().nonnegative().max(1000000000).default(0) });
export const saleSchema = z.object({ customerId: z.string().uuid(), items: z.array(z.object({ productId: z.string().uuid(), quantity: z.number().int().positive().max(1000000000), unitPrice: money.optional() })).min(1).max(500).refine(uniqueProducts, 'Each product must appear only once') });
export const supplierSchema = z.object({ name: safeName, email: z.string().trim().email().max(254).optional(), phone: phone.optional() });
export const purchaseSchema = z.object({ supplierId: z.string().uuid(), items: z.array(z.object({ productId: z.string().uuid(), quantity: z.number().int().positive().max(1000000000), unitCost: money.optional() })).min(1).max(500).refine(uniqueProducts, 'Each product must appear only once') });
export const employeeSchema = z.object({ name: safeName, email: z.string().trim().email().max(254).optional(), department: safeShortText(80).optional(), position: safeShortText(80).optional(), status: z.enum(['active', 'inactive']).default('active') });
export const projectSchema = z.object({ name: safeName, customerId: z.string().uuid().optional(), ownerId: z.string().uuid(), startsOn: isoDate.optional(), endsOn: isoDate.optional() }).refine(project => !project.startsOn || !project.endsOn || project.endsOn >= project.startsOn, { message: 'End date must be on or after start date', path: ['endsOn'] });
export const taskSchema = z.object({ title: safeShortText(160).refine(value => value.length >= 2, 'Too short'), assigneeId: z.string().uuid().optional(), dueOn: isoDate.optional() });
export const transactionSchema = z.object({ type: z.enum(['income', 'expense']), category: safeShortText(80).refine((value) => value.length >= 2, 'Too short'), amount: positiveMoney, status: z.enum(['pending', 'paid']).default('pending'), reference: safeShortText(120).optional() });
export const documentSchema = z.object({ name: z.string().trim().min(1).max(160), category: safeShortText(80).refine(value => value.length >= 1, 'Required'), storageKey: z.string().trim().min(1).max(500), entity: safeShortText(80).optional(), entityId: z.string().uuid().optional() });
export const documentUploadSchema = z.object({ name: z.string().trim().min(1).max(160), category: safeShortText(80).refine(value => value.length >= 1, 'Required'), contentBase64: z.string().min(1).max(14_000_000).regex(/^[A-Za-z0-9+/]*={0,2}$/, 'Invalid base64 content'), extension: z.string().trim().toLowerCase().regex(/^[a-z0-9]{1,10}$/, 'Invalid extension').optional(), entity: safeShortText(80).optional(), entityId: z.string().uuid().optional() });
export const incidentSchema = z.object({ title: safeShortText(160).refine((value) => value.length >= 2, 'Too short'), description: z.string().trim().max(2000).optional() });
export const productionSchema = z.object({ productId: z.string().uuid(), quantity: z.number().int().positive().max(1000000000) });
export const quoteSchema = z.object({ customerId: z.string().uuid(), items: z.array(z.object({ productId: z.string().uuid(), quantity: z.number().int().positive().max(1000000000), unitPrice: money })).min(1).max(500).refine(uniqueProducts, 'Each product must appear only once'), taxRate: z.number().finite().min(0).max(1).default(0) });
export const paymentSchema = z.object({ type: z.enum(['sale', 'purchase', 'income', 'expense']), referenceId: z.string().uuid(), amount: positiveMoney, method: z.enum(['cash', 'bank_transfer', 'card', 'external']) });
export const branchSchema = z.object({ name: safeName, address: z.string().trim().max(240).optional(), active: z.boolean().default(true) });
export const warehouseSchema = z.object({ name: safeName, branchId: z.string().uuid().optional() });
export const bomSchema = z.object({ productId: z.string().uuid(), components: z.array(z.object({ productId: z.string().uuid(), quantity: z.number().int().positive().max(1000000000) })).min(1).max(500).refine(uniqueProducts, 'Each component must appear only once') }).refine(bom => !bom.components.some(item => item.productId === bom.productId), 'A product cannot consume itself');
export const movementSchema = z.object({ productId: z.string().uuid(), type: z.enum(['in', 'out']), quantity: z.number().int().positive().max(1000000000) });
export const registerSchema = z.object({ email: z.string().trim().email().max(254), name: safeName, companyName: safeName, password: z.string().min(8).max(72), planId: z.enum(['starter', 'professional', 'business']).default('starter'), billingCycle: z.enum(['monthly', 'annual']).default('monthly'), modules: z.array(z.enum(['crm','sales','inventory','purchases','finance','hr','projects','reports'])).max(8).refine(items => new Set(items).size === items.length, 'Modules must be unique').optional(), industry: safeShortText(80).optional(), employeeCount: z.number().int().min(1).max(1000000).optional(), country: safeName.default('México'), taxId: z.string().trim().max(32).regex(/^[A-Za-z0-9&Ññ-]*$/, 'Invalid tax ID').optional() });
